name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Checkout submodules
      uses: textbook/git-checkout-submodule-action@2.0.0
    - name: Build library-metamorphic-testing
      run: cd third_party/library-metamorphic-testing/ && mkdir build && cd build && cmake -DCMAKE_BUILD_TYPE=Release -DMETALIB_LIB_ONLY=ON -DYAML_BUILD_SHARED_LIBS=ON .. && make -j && cd ../../..
    - name: Link library
      run: mkdir libs && ln -s `pwd`/third_party/library-metamorphic-testing/build/libmetalib_fuzz.so ./libs
    - name: Build
      run: mkdir build && cd build && cmake -G Ninja .. && ninja
